#!/usr/bin/env bash
#  installing nginx web server on remote server

# Update packages
apt-get -y update

# install Nginx
apt-get -y install nginx

# allowing incoming HTTP traffic
ufw allow 'Nginx HTTP'

# return a page that contains the string Hello World!
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# starting Nginx service
service nginx start
