#!/usr/bin/env bash
# a bash script that runs Nginx, and listens on port 80 of all the server’s active IPv4 IPs


rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
