#!/usr/bin/env bash\
# Bash script that install Nginx in 5 or less lines long
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
service nginx status | grep -q "not running" && echo "Nginx is not running"
