#!/usr/bin/env bash
# a Bash script that displays a list of currently running processes.
# it must show all processes, for all users, including those which might not have a TTY
# it display in a user-oriented format
# Show process hierarchy

ps axuf
