#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process
# You must use kill
# get the pid

pid=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# infinity process termination

if [ -n "$pid" ];
then
	kill "$pid"
fi
