#!/usr/bin/env bash
# a Bash script that displays the content of the file "/etc/passwd"
# display:
#	-username
#	-user id
#	-Home directory path for the user
# using while loop

while IFS=: read -r content
do
	echo "$content" | cut -f 1, 3, 6 -d ':'
done < "/etc/passwd"
