#!/usr/bin/env bash
# a Bash script that displays Best School 10 times
# for the 9th iteration, displays Best School and then Hi on a new line

n_cont=0

while [ $n_cont -lt 10 ]
do
	if [ $n_cont -eq 9 ]
	then
		echo "Hi"
	fi
		echo "Best School"
	((n_cont++))
done
