#!/usr/bin/env bash
# a Bash script that loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

n_cont=0

while [ $n_cont -lt 10 ]
do
	if [ $n_cont -eq 3 ]
	then
		echo "bad luck"
	elif [ $n_cont -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((n_cont ++))
	
done
