#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
# it displays 4 and then bad luck from China for the 4th loop iteration
# it displays 9 and then bad luck from Japan for the 9th loop iteration
# it displays 17 and then bad luck from Italy for the 17th loop iteration

n_cont=1

while [ $n_cont -le 20 ]
do
	echo "$n_cont"
	case $n_cont in
		"4") echo "bad luck from China";
		"9") echo "bad luck from Japan";
		"17") echo "bad luck from Italy";
	esac
	((n_cont++))
done
