#!/usr/bin/env bash
# a Bash script that configures the container to allow nginx running as nginx user, nginx should be listening on all active IPs on port 8080
chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
